import type { Dentist, Specialty } from "@/types/dentist";

export const DENTISTS: Dentist[] = [
  {
    id: 1,
    name: "Dra. Carolina Mendes",
    cro: "CRO-SP 123456",
    specialty: "Estética Dental",
    rating: 5.0,
    reviews: 312,
    distance: "1.2 km",
    price: "R$ 180",
    available: true,
    availabilityLabel: "Atende hoje",
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=200&h=200&fit=crop&auto=format&q=80",
    city: "Consolação, SP",
    neighborhood: "Consolação",
    hours: "Seg-Sex 8h-18h",
    convenios: 5,
    tags: ["Clareamento", "Estética", "Limpeza"],
  },
  {
    id: 2,
    name: "Dra. Patrícia Ferreira",
    cro: "CRO-SP 234567",
    specialty: "Odontopediatria",
    rating: 4.9,
    reviews: 289,
    distance: "0.8 km",
    price: "R$ 220",
    available: true,
    availabilityLabel: "Atende hoje",
    photo: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=200&h=200&fit=crop&auto=format&q=80",
    city: "Jardins, SP",
    neighborhood: "Jardins",
    hours: "Seg-Sex 8h-17h",
    convenios: 4,
    tags: ["Infantil", "Limpeza", "Canal"],
  },
  {
    id: 3,
    name: "Dr. Marcos Vieira",
    cro: "CRO-SP 345678",
    specialty: "Implantodontia",
    rating: 4.9,
    reviews: 241,
    distance: "3.7 km",
    price: "R$ 250",
    available: false,
    availabilityLabel: "Poucos horários",
    photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=200&h=200&fit=crop&auto=format&q=80",
    city: "Jardim América, SP",
    neighborhood: "Jardim América",
    hours: "Seg-Sex 8h-18h",
    convenios: 3,
    tags: ["Cirurgia", "Implante"],
  },
  {
    id: 4,
    name: "Dra. Amanda Oliveira",
    cro: "CRO-SP 456789",
    specialty: "Ortodontia",
    rating: 4.9,
    reviews: 198,
    distance: "2.1 km",
    price: "R$ 200",
    available: true,
    availabilityLabel: "Atende hoje",
    photo: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=200&h=200&fit=crop&auto=format&q=80",
    city: "Pinheiros, SP",
    neighborhood: "Pinheiros",
    hours: "Seg-Sáb 8h-17h",
    convenios: 6,
    tags: ["Aparelho", "Ortodontia"],
  },
  {
    id: 5,
    name: "Dr. Rafael Souza",
    cro: "CRO-SP 567890",
    specialty: "Endodontia",
    rating: 4.8,
    reviews: 174,
    distance: "4.5 km",
    price: "R$ 310",
    available: true,
    availabilityLabel: "Atende hoje",
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=200&h=200&fit=crop&auto=format&q=80",
    city: "Itaim Bibi, SP",
    neighborhood: "Itaim Bibi",
    hours: "Seg-Sex 7h-19h",
    convenios: 5,
    tags: ["Canal", "Endodontia"],
  },
  {
    id: 6,
    name: "Dra. Fernanda Costa",
    cro: "CRO-SP 678901",
    specialty: "Periodontia",
    rating: 4.8,
    reviews: 163,
    distance: "1.9 km",
    price: "R$ 190",
    available: false,
    availabilityLabel: "Amanhã disponível",
    photo: "https://images.unsplash.com/photo-1643297654416-05795d62e39c?w=200&h=200&fit=crop&auto=format&q=80",
    city: "Vila Madalena, SP",
    neighborhood: "Vila Madalena",
    hours: "Ter-Sáb 9h-18h",
    convenios: 4,
    tags: ["Limpeza", "Periodontia", "Estética"],
  },
  {
    id: 7,
    name: "Dr. Gustavo Lima",
    cro: "CRO-SP 789012",
    specialty: "Prótese Dentária",
    rating: 4.8,
    reviews: 152,
    distance: "2.8 km",
    price: "R$ 280",
    available: true,
    availabilityLabel: "Atende hoje",
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=200&h=200&fit=crop&auto=format&q=80",
    city: "Moema, SP",
    neighborhood: "Moema",
    hours: "Seg-Sex 8h-18h",
    convenios: 3,
    tags: ["Prótese", "Implante"],
  },
  {
    id: 8,
    name: "Dra. Juliana Ramos",
    cro: "CRO-SP 890123",
    specialty: "Clínico Geral",
    rating: 4.7,
    reviews: 208,
    distance: "0.5 km",
    price: "R$ 150",
    available: true,
    availabilityLabel: "Atende hoje",
    photo: "https://images.unsplash.com/photo-1612276529731-4b21494e6d71?w=200&h=200&fit=crop&auto=format&q=80",
    city: "Bela Vista, SP",
    neighborhood: "Bela Vista",
    hours: "Seg-Sex 8h-18h",
    convenios: 7,
    tags: ["Limpeza", "Clareamento", "Urgência"],
  },
  {
    id: 9,
    name: "Dr. Eduardo Nunes",
    cro: "CRO-SP 901234",
    specialty: "Cirurgia Oral",
    rating: 4.7,
    reviews: 187,
    distance: "5.2 km",
    price: "R$ 350",
    available: false,
    availabilityLabel: "Poucos horários",
    photo: "https://images.unsplash.com/photo-1638202993928-7267aad84c31?w=200&h=200&fit=crop&auto=format&q=80",
    city: "Santo André, SP",
    neighborhood: "Santo André",
    hours: "Seg-Sex 7h-17h",
    convenios: 4,
    tags: ["Cirurgia", "Implante", "Prótese"],
  },
  {
    id: 10,
    name: "Dra. Isabela Martins",
    cro: "CRO-SP 012345",
    specialty: "Odontologia Estética",
    rating: 4.6,
    reviews: 143,
    distance: "3.1 km",
    price: "R$ 230",
    available: true,
    availabilityLabel: "Atende hoje",
    photo: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=200&h=200&fit=crop&auto=format&q=80",
    city: "Perdizes, SP",
    neighborhood: "Perdizes",
    hours: "Seg-Sáb 9h-19h",
    convenios: 5,
    tags: ["Estética", "Clareamento", "Aparelho"],
  },
];

export const SPECIALTIES: Specialty[] = [
  { id: "clinico", label: "Clínico Geral", icon: "Stethoscope", count: 450 },
  { id: "urgencia", label: "Urgência", icon: "Siren", count: 76 },
  { id: "dor", label: "Dor de Dente", icon: "Zap", count: 134 },
  { id: "aparelho", label: "Aparelho", icon: "AlignCenter", count: 142 },
  { id: "clareamento", label: "Clareamento", icon: "Sparkles", count: 201 },
  { id: "limpeza", label: "Limpeza", icon: "Droplets", count: 389 },
  { id: "implante", label: "Implante", icon: "Wrench", count: 89 },
  { id: "canal", label: "Canal", icon: "Activity", count: 67 },
  { id: "protese", label: "Prótese", icon: "Layers", count: 54 },
  { id: "estetica", label: "Estética", icon: "Star", count: 201 },
  { id: "infantil", label: "Infantil", icon: "Baby", count: 118 },
  { id: "cirurgia", label: "Cirurgia", icon: "Scissors", count: 43 },
];

// ─── Atividades disponíveis para cadastro e exibição ────────────────────────
// Fonte canônica — mesma lista usada em NovoCadastro e MeuPerfil
export const ESPECIALIDADES: string[] = [
  "Clínico Geral",
  "Clareamento dental",
  "Lentes de contato dental",
  "Facetas de porcelana",
  "Limpeza e profilaxia",
  "Ortodontia (aparelho)",
  "Implante dentário",
  "Tratamento de canal",
  "Prótese dentária",
  "Cirurgia oral",
  "Periodontia",
  "Odontopediatria",
  "Botox odontológico",
  "Harmonização orofacial",
];

